"""MechAgent 工具抽象层公开接口。"""

from mechagent.core.cad import (
    AbstractCADKernel,
    CADConfig,
    CADGeometryFeature,
    CADGeometrySummary,
    CADImportResult,
    GeometryCandidate,
    RegionCandidate,
    geometry_candidate_from_summary,
)
from mechagent.core.exceptions import (
    CADError,
    ExecutorError,
    MechAgentCoreError,
    MeshError,
    PostProcError,
    SolverError,
)
from mechagent.core.executor import (
    AbstractJobExecutor,
    ExecutorConfig,
    JobResult,
    JobSpec,
    JobStatus,
    LocalCommandExecutor,
)
from mechagent.core.factory import (
    create_cad_kernel,
    create_executor,
    create_mesher,
    create_solver,
    register_cad_kernel,
    register_executor,
    register_mesher,
    register_solver,
    registered_cad_kernels,
    registered_executors,
    registered_meshers,
    registered_solvers,
    unregister_cad_kernel,
    unregister_executor,
    unregister_mesher,
    unregister_solver,
)
from mechagent.core.materials import BUILTIN_MATERIALS, MaterialDefinition, match_builtin_material
from mechagent.core.mesher import AbstractMesher, MeshConfig, MeshResult
from mechagent.core.postproc import PostProcessor
from mechagent.core.rules import (
    RuleViolation,
    check_parameter_ranges,
    check_static_execution_contract,
    ensure_parameter_ranges,
    ensure_static_execution_contract,
)
from mechagent.core.solver import AbstractSolver, SolverConfig, SolverResult

__all__ = [
    "AbstractCADKernel",
    "AbstractJobExecutor",
    "AbstractMesher",
    "AbstractSolver",
    "BUILTIN_MATERIALS",
    "CADConfig",
    "CADError",
    "CADGeometryFeature",
    "CADGeometrySummary",
    "CADImportResult",
    "ExecutorConfig",
    "GeometryCandidate",
    "RegionCandidate",
    "geometry_candidate_from_summary",
    "ExecutorError",
    "JobResult",
    "JobSpec",
    "JobStatus",
    "LocalCommandExecutor",
    "MaterialDefinition",
    "MechAgentCoreError",
    "MeshConfig",
    "MeshError",
    "MeshResult",
    "PostProcError",
    "PostProcessor",
    "RuleViolation",
    "SolverConfig",
    "SolverError",
    "SolverResult",
    "create_cad_kernel",
    "create_executor",
    "create_mesher",
    "create_solver",
    "check_static_execution_contract",
    "register_cad_kernel",
    "register_executor",
    "register_mesher",
    "register_solver",
    "registered_cad_kernels",
    "registered_executors",
    "registered_meshers",
    "registered_solvers",
    "unregister_cad_kernel",
    "unregister_executor",
    "unregister_mesher",
    "unregister_solver",
    "check_parameter_ranges",
    "ensure_parameter_ranges",
    "ensure_static_execution_contract",
    "match_builtin_material",
]
